apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer-config
data:
  network.json: |-
      {
      "name": "first-network",
      "version": "1.0.0",
      "client": {
        "tlsEnable": true,
        "adminCredential": {
          "id": "admin",
          "password": "adminpw"
        },
        "enableAuthentication": true,
        "organization": "Org1MSP",
        "connection": {
          "timeout": {
            "peer": {
              "endorser": "300"
            },
            "orderer": "300"
          }
        }
      },
      "channels": {
        "mychannel": {
          "peers": {
            "peer0-org1": {}
          },
          "connection": {
            "timeout": {
              "peer": {
                "endorser": "6000",
                "eventHub": "6000",
                "eventReg": "6000"
              }
            }
          }
        }
      },
      "organizations": {
        "Org1MSP": {
          "mspid": "Org1MSP",
          "adminPrivateKey": {
            "path": "/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk"
          },
          "peers": [
            "peer0-org1"
          ],
          "signedCert": {
            "path": "/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem"
          }
        }
      },
      "peers": {
        "peer0-org1": {
          "tlsCACerts": {
            "path": "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
          },
          "url": "grpcs://peer0-org1:7051"
        }
      }
      }

  config.json: |- 
      {
      "network-configs": {
        "first-network": {
          "name": "first-network",
          "profile": "./first-network.json"
        }
      },
      "license": "Apache-2.0"
      }
