apiVersion: batch/v1
kind: Job
metadata:
  name: create-app-channel
spec:
  backoffLimit: 2
  parallelism: 1 # maksiumum çalıştırılacak pod
  completions: 1
  template:
    spec:
      containers:
      - name: create-app-channel
        image: hyperledger/fabric-tools:2.3
        workingDir: /
        command:
          - /bin/bash
          - -c
          - |
            ./scripts/createAppChannel.sh
        env:
          - name: ORDERER_CA # orderer ca konfigurasyonu
            value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
          - name: CORE_PEER_ADDRESS # peer adresi
            value: peer0-org1:7051
          - name: CORE_PEER_ID
            value: cli.peer0.org1.example.com
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
          - name: CORE_PEER_TLS_CERT_FILE
            value: /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_KEY_FILE
            value: /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
          - name: FABRIC_LOGGING_SPEC
            value: ERROR
          - name: GOPATH
            value: /opt/gopath
          - name: SYS_CHANNEL
            value: system-channel
          - name: CORE_CHAINCODE_BUILDER
            value: hyperledger/fabric-ccenv:1.4.8
        volumeMounts:
            - name: fabricfiles
              mountPath: /organizations
              subPath: organizations # sertifikalara erişmek için
            - name: fabricfiles
              mountPath: /configtx
              subPath: configtx # configtx.yaml dosyası için.
            - name: fabricfiles
              mountPath: /channel-artifacts
              subPath: channel-artifacts # channel artifact dir
            - name: fabricfiles
              mountPath: /scripts
              subPath: scripts
            - name: fabricfiles
              mountPath: /opt/gopath/src/github.com/chaincode
              subPath: chaincode # chanicode dir
      restartPolicy: OnFailure
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabricfiles-pvc