apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-peer0-org2
  labels:
    app: cli-peer0-org2
spec:
  selector:
    matchLabels:
      app: cli-peer0-org2
  template:
    metadata:
      labels:
        app: cli-peer0-org2
    spec:
      containers:
      - name: cli-peer0-org2
        image: hyperledger/fabric-tools:2.3
        workingDir: /
        stdin: true
        tty: true
        resources:
          requests:
            memory: "200Mi"
            cpu: "90m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        env:
          - name: ORDERER_CA # orderer ca konfigurasyonu
            value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
          - name: CORE_PEER_ADDRESS # peer adresi
            value: peer0-org2:7051
          - name: CORE_PEER_ID
            value: cli.peer0.org2.example.com
          - name: CORE_PEER_LOCALMSPID
            value: Org2MSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
          - name: CORE_PEER_TLS_CERT_FILE
            value: /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_KEY_FILE
            value: /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
          - name: FABRIC_LOGGING_SPEC
            value: ERROR
          - name: GOPATH
            value: /opt/gopath
          - name: SYS_CHANNEL
            value: system-channel
        volumeMounts:
            - name: fabricfiles
              mountPath: /organizations
              subPath: organizations # sertifikalara erişmek için
            - name: fabricfiles
              mountPath: /configtx
              subPath: configtx # configtx.yaml dosyası için.
            - name: fabricfiles
              mountPath: /channel-artifacts
              subPath: channel-artifacts # channel artifact dir
            - name: fabricfiles
              mountPath: /scripts
              subPath: scripts
            - name: fabricfiles
              mountPath: /opt/gopath/src/github.com/chaincode
              subPath: chaincode # chanicode dir
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabricfiles-pvc
